// ITEMS
export const MOVE_ITEM = "MOVE_ITEM";
export const ROTATE_ITEM = "ROTATE_ITEM";
export const RESIZE_ITEM = "RESIZE_ITEM";
export const SELECT_ITEM = "SELECT_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const SET_CREATED_ITEM = "SET_CREATED_ITEM";
export const CREATE_ITEM = "CREATE_ITEM";
export const REFRESH_CORNERS_ITEM = "REFRESH_CORNERS_ITEM";
export const REFRESH_PATH_BOX_ITEM = "REFRESH_PATH_BOX_ITEM";

export const MOVE_ITEMS = "MOVE_ITEMS";
export const ROTATE_ITEMS = "ROTATE_ITEMS";
export const RESIZE_ITEMS = "RESIZE_ITEMS";
export const SELECT_ITEMS = "SELECT_ITEMS";
export const DELETE_ITEMS = "DELETE_ITEMS";
export const REFRESH_CORNERS_ITEMS = "REFRESH_CORNERS_ITEMS";
export const REFRESH_PATH_BOX_ITEMS = "REFRESH_PATH_BOX_ITEMS";

// GROUPS
export const MOVE_GROUP = "MOVE_GROUP";
export const ROTATE_GROUP = "ROTATE_GROUP";
export const RESIZE_GROUP = "RESIZE_GROUP";
export const SELECT_GROUP = "SELECT_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const CREATE_GROUP = "CREATE_GROUP";
export const REFRESH_CORNERS_GROUP = "REFRESH_CORNERS_GROUP";

export const MOVE_GROUPS = "MOVE_GROUPS";
export const ROTATE_GROUPS = "ROTATE_GROUPS";
export const RESIZE_GROUPS = "RESIZE_GROUPS";
export const SELECT_GROUPS = "SELECT_GROUPS";
export const DELETE_GROUPS = "DELETE_GROUPS";
export const REFRESH_CORNERS_GROUPS = "REFRESH_CORNERS_GROUPS";

// SELECTION
export const SET_SELECTION = "SET_SELECTION";
export const ROTATE_SELECTION = "ROTATE_SELECTION";

// PATH EDITOR
export const OPEN_PATH_EDITOR = "OPEN_PATH_EDITOR";
export const SELECT_PATH_POINT = "SELECT_PATH_POINT";
export const SELECT_BEZIER_POINT = "SELECT_BEZIER_POINT";
export const SHOW_NEW_PATH_POINT = "SHOW_NEW_PATH_POINT";
export const CREATE_PATH_POINT = "CREATE_PATH_POINT";
export const DELETE_PATH_POINT = "DELETE_PATH_POINT";
export const UPDATE_PATH_EDITOR_POINTS = "UPDATE_PATH_EDITOR_POINTS";
export const MOVE_PATH_POINT = "MOVE_PATH_POINT";
export const MOVE_BEZIER_POINT = "MOVE_BEZIER_POINT";
export const TOGGLE_BEZIER_POINT = "TOGGLE_BEZIER_POINT";
